# Generated by Django 4.2.5 on 2023-09-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='end_time',
            new_name='end_time_default',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='start_time',
            new_name='start_time_default',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='посещения', to='worktime.attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
