# Generated by Django 4.2.5 on 2023-09-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0002_rename_end_time_attendance_end_time_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='worktime.employee'),
        ),
    ]
