# Generated by Django 4.2.5 on 2023-09-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0005_remove_attendance_employees_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time_default',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time_default',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
