# Generated by Django 4.2.5 on 2023-09-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0006_alter_attendance_end_time_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='end_time_default',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='start_time_default',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_time',
        ),
        migrations.AddField(
            model_name='office',
            name='end_time_default',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='start_time_default',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='worktime.employee'),
        ),
    ]
