# Generated by Django 4.2.5 on 2023-09-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0008_alter_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office', to='worktime.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='end_time_default',
            field=models.TimeField(blank=True, default='19:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='start_time_default',
            field=models.TimeField(blank=True, default='10:00:00', null=True),
        ),
    ]
