# Generated by Django 4.2.5 on 2023-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0010_remove_office_end_time_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deadline',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_time_default',
            field=models.TimeField(default='19:00:00'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time_default',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
