# Generated by Django 4.2.5 on 2023-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0011_employee_deadline_alter_employee_end_time_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lateness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
