# Generated by Django 4.2.5 on 2023-09-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0013_alter_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='end_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='start_time',
            new_name='care_time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='end_time_default',
            new_name='end_workday',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='start_time_default',
            new_name='getting_started',
        ),
    ]
